name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16"

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Generate
        run: |
          go run github.com/prisma/prisma-client-go prefetch
          go run github.com/prisma/prisma-client-go generate --schema data/schema.prisma

      # - name: Vet
      #   run: go vet .

      - name: Lint
        run: golint .

      # - name: Static Check
      #   run: staticcheck ./...

      # - name: Test
      #   run: go test ./...
